spring:
  application:
    name: Authentication-System

  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: iHave@2023Kurtas
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   database-platform: org.hibernate.dialect.MySQL8Dialect
   hibernate:
      ddl-auto: update
